version: '3.8'

services:
  db_postgres:
      container_name: db_postgres
      image: postgres:alpine3.16
      ports:
        - "5432:${DATABASE_PORT}"
      environment:
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      restart: always
      volumes:
        - db_postgres:/var/lib/postgresql/data

#  ticket_support_bot:
#          build: .
#          container_name: ticket_support_bot
#          restart: always
#          ports:
#            - "${PANEL_PORT}:${PANEL_PORT}"
#          depends_on:
#            - db_postgres
#          volumes:
#            - /root/ticket_support_bot/storage:/usr/src/app/ticket_support_bot/storage
#            - /root/ticket_support_bot/logs:/usr/src/app/ticket_support_bot/logs

volumes:
  db_postgres: